# Generated by Django 4.2.9 on 2024-01-14 19:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('floors', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_available', models.BooleanField(default=True)),
                ('at_floor', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', related_query_name='building', to='rooms.building')),
            ],
        ),
    ]
